### ISSUE TITLE
pairadise computes p-value problems

### ISSUE THREAD

**Issue by forever-happy-h** [Xinglab/PAIRADISE#14] opened 2023-12-25 12:11 UTC
Hi Eric Kutschera,

When I extract the result file RI.MATS.JC.txt then extract the key information in it, as shown below:

RI.p<-RI[,c("ID", "IJC_SAMPLE_1", "SJC_SAMPLE_1", "IJC_SAMPLE_2",

        "SJC_SAMPLE_2", "IncFormLen", "SkipFormLen")]
But when I use pairadise to calculate the p-value. He had a problem with data mismatch.As shown below:

Error in load.data(my.data) :
Error with data: some data are not matched pairs.

I also looked at your scripts on github and found that the two sample sizes don't match up. But we're using rMATs to start with the bam file and he's able to compute p-values.

But I also checked the commands in your paired_model.R file and found that it was the same as the commands we ran. Why did yours have no errors and corresponding results while mine did not? Even though I filled 0 for it to make their sample numbers consistent, the final result was still different from that of rMATs.

So I take the liberty of writing to ask you. Sorry about that.

Here I first say thank you!

**Comment by EricKutschera** [comment] 2023-12-26 19:40
Duplicate of https://github.com/Xinglab/rmats-turbo/issues/350

**Closed as completed by EricKutschera** 2023-12-26 19:40 UTC
